version: 2
updates:
- package-ecosystem: npm
  directory: "/examples/prisma"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples/jwt-auth-typeorm"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - satishbabariya
  assignees:
  - satishbabariya
